@startuml "Alocar Motorista"
hide footbox

actor GestorFrota as gestor_ator
participant TelaAlocacao as tela_alocacao
participant ControleAlocacao as controle_alocacao
participant BD as bd

gestor_ator -> tela_alocacao: selecionarMotoristaEVeiculo(id_motorista: int, id_veiculo: int)
activate tela_alocacao

tela_alocacao -> controle_alocacao: validarDisponibilidade(id_motorista: int, id_veiculo: int)
activate controle_alocacao

controle_alocacao -> controle_alocacao: verificarDisponibilidade(id_motorista: int, id_veiculo:int)
activate controle_alocacao

deactivate controle_alocacao

controle_alocacao -> bd: registrarAlocacao(id_motorista: int, id_veiculo: int)
activate bd

bd --> controle_alocacao

deactivate bd

controle_alocacao -> tela_alocacao: exibirMensagem("Motorista alocado com sucesso")
deactivate controle_alocacao

deactivate tela_alocacao
@enduml
