@startuml "Cadastrar Veículo"
hide footbox

actor GestorFrota as gestor_ator
participant TelaCadastroVeiculo as tela_cadastro_veiculo
participant ControleVeiculo as controle_veiculo
participant BD as bd

gestor_ator -> tela_cadastro_veiculo: selecionarOpcaoCadastrarVeiculo()
activate tela_cadastro_veiculo

tela_cadastro_veiculo -> controle_veiculo: solicitarDadosVeiculo()
activate controle_veiculo

controle_veiculo -> bd: salvarVeiculo(placa: int, modelo: String, ano: int, tipo: String, dispositivoRastreamento: int)
activate bd

bd --> controle_veiculo: sucesso

deactivate bd
controle_veiculo -> tela_cadastro_veiculo: exibirMensagem("Veículo cadastrado com sucesso")
deactivate controle_veiculo

deactivate tela_cadastro_veiculo
@enduml
