@startuml "Conhecer o Trajeto Percorrido"
hide footbox

actor GestorFrota as gestor_ator
participant TelaTrajeto as tela_trajeto
participant ControleRastreamento as controle_rastreamento
participant BD as bd

gestor_ator -> tela_trajeto: solicitarTrajeto(id_veiculo)
activate tela_trajeto

tela_trajeto -> controle_rastreamento: obterTrajeto(id_veiculo)
activate controle_rastreamento

controle_rastreamento -> bd: consultarHistoricoTrajetos(id_veiculo)
activate bd

bd --> controle_rastreamento: retornarHistorico()
deactivate bd

controle_rastreamento --> tela_trajeto: exibirHistorico()
deactivate controle_rastreamento

deactivate tela_trajeto
@enduml