@startuml "Corrigir ou Advertir Motoristas"
hide footbox

actor GestorFrota as gestor_ator
participant ControleTelemetria as controle_telemetria
participant BD as bd

gestor_ator -> controle_telemetria: obterEventosRecente()
activate controle_telemetria

controle_telemetria -> bd: consultarEventos(id_veiculo: int)
activate bd

bd --> controle_telemetria: retornarEventos()
deactivate bd

gestor_ator -> controle_telemetria: emitirAdvertencia(evento: String, mensagem: String)
controle_telemetria -> bd: salvarAdvertencia(mensagem: String)
activate bd

bd --> controle_telemetria: sucesso

deactivate bd

deactivate controle_telemetria
@enduml
