@startuml "Gerenciar Manutenção"
hide footbox

actor GestorFrota as gestor_ator
participant TelaManutencao as tela_manutencao
participant ControleManutencao as controle_manutencao
participant BD as bd

gestor_ator -> tela_manutencao: cadastrarManutencao(id_veiculo: int, tipo: String, data: Date)
activate tela_manutencao

tela_manutencao -> controle_manutencao: validarDados(id_veiculo: int, tipo: String, data: Date)
activate controle_manutencao

controle_manutencao -> bd: salvarManutencao(id_veiculo: int, tipo: String, data: Date)
activate bd

bd --> controle_manutencao: confirmaçãoCadastro()
deactivate bd

controle_manutencao --> tela_manutencao: exibirMensagem("Manutenção registrada com sucesso")
deactivate controle_manutencao

deactivate tela_manutencao
@enduml
