@startuml "Saber a Velocidade do Veículo"
hide footbox

actor GestorFrota as gestor_ator
participant TelaVelocidade as tela_velocidade
participant ControleTelemetria as controle_telemetria
participant BD as bd

gestor_ator -> tela_velocidade: solicitarVelocidade(id_veiculo)
activate tela_velocidade

tela_velocidade -> controle_telemetria: obterVelocidade(id_veiculo)
activate controle_telemetria

controle_telemetria -> bd: consultarVelocidade(id_veiculo)
activate bd

bd --> controle_telemetria: retornarVelocidade()
deactivate bd

controle_telemetria --> tela_velocidade: exibirVelocidade()
deactivate controle_telemetria

deactivate tela_velocidade
@enduml