# Generated by Django 4.2.3 on 2025-02-20 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnh', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('status', models.CharField(choices=[('disponível', 'Disponível'), ('em uso', 'Em Uso'), ('manutenção', 'Manutenção')], max_length=50)),
                ('frota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frotas.frota')),
            ],
        ),
        migrations.CreateModel(
            name='Rastreamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=255)),
                ('horario', models.DateTimeField(auto_now_add=True)),
                ('velocidade', models.FloatField()),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frotas.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('custo', models.FloatField()),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frotas.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='EventoTelemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frotas.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frotas.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frotas.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertenciaMotorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frotas.motorista')),
            ],
        ),
    ]
