@startuml "Diagrama de caso e uso"

left to right direction

:Gestor de Frotas: as gestor_de_frotas

rectangle "Geremciamento de Frotas"{
    (Rastrear Veiculos) as rastrear_veiculos
    (Gerenciar Manutencao) as gerenciar_manutencao
    (Visualizar Historico de Localizacao) as visualizar_historico_de_localizacao
    (Localizar Veiculo) as localizar_veiculo
    (Identificar Telemetria) as identificar_telemetria
    (Identificar Tempo de Veiculo Parado) as identificar_tempo_de_veiculo_parado
    (Conhecer Trajeto Pecorrido) as conhecer_trajeto_pecorrido
    (Cadastrar Veiculo) as cadastrar_veiculo
    (Listar Veiculo) as listar_veiculo
    (Alocar) as alocar
    (Corrigir Motorista) as corrigir_motorista
} 

gestor_de_frotas --> rastrear_veiculos
gestor_de_frotas --> gerenciar_manutencao
gestor_de_frotas --> visualizar_historico_de_localizacao
gestor_de_frotas --> alocar
gestor_de_frotas --> cadastrar_veiculo
gestor_de_frotas --> listar_veiculo

visualizar_historico_de_localizacao <.. identificar_tempo_de_veiculo_parado: <<extend>>
visualizar_historico_de_localizacao <.. conhecer_trajeto_pecorrido: <<extend>>
rastrear_veiculos ..> localizar_veiculo: <<include>>
localizar_veiculo <.. identificar_telemetria: <<extend>>

alocar <.. corrigir_motorista: <<extend>>

@enduml
